# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqquestion',
            name='created',
        ),
        migrations.RemoveField(
            model_name='faqquestion',
            name='updated',
        ),
        migrations.AddField(
            model_name='faqquestion',
            name='slug',
            field=models.SlugField(default='test', help_text=b'Used to make a nice url for the page that displays this.'),
            preserve_default=False,
        ),
    ]
