# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_auto_20160602_1644'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='FAQQuestionPage',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('faqpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faq.FAQPage', verbose_name=b'page')),
                    ],
                    options={
                        'db_table': 'faq_faqquestion_pages',
                    },
                ),
                migrations.AlterField(
                    model_name='faqquestion',
                    name='pages',
                    field=models.ManyToManyField(blank=True, related_name='questions', through='faq.FAQQuestionPage', to='faq.FAQPage'),
                ),
                migrations.AddField(
                    model_name='faqquestionpage',
                    name='faqquestion',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_to_page', to='faq.FAQQuestion', verbose_name=b'question'),
                ),
            ],
            database_operations=[]
        )
    ]
