# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_auto_20160606_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqquestionpage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='faqquestionpage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
