# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0007_schedule_private'),
        ('faq', '0005_auto_20160606_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqpage',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text=b'Which schedule is this related to? If the schedule is private, this page will be kept private too.', null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.Schedule'),
        ),
    ]
