# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 11:55
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import markitup.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conference', '0009_auto_20160610_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, help_text=b'An internal name for this document, to help identify it.', max_length=1024)),
                ('title', models.CharField(help_text=b'The title for this document that will be shown to the user.', max_length=1024)),
                ('description', markitup.fields.MarkupField(blank=True, no_rendered_field=True)),
                ('file', models.FileField(upload_to=b'documents/')),
                ('_description_rendered', models.TextField(blank=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, help_text=b'An internal name for this theme, to help identify it.', max_length=1024)),
                ('title', models.CharField(help_text=b'The page title that will be shown to the user when they view this theme.', max_length=1024)),
                ('slug', autoslug.fields.AutoSlugField(editable=True, help_text=b"Used to make a nice url for this Theme's page.", populate_from=b'title', unique=True)),
                ('content', markitup.fields.MarkupField(blank=True, no_rendered_field=True)),
                ('_content_rendered', models.TextField(blank=True, editable=False)),
                ('schedules', models.ManyToManyField(blank=True, help_text=b'Which schedules is this related to? If a schedule is private, this theme will be kept private too, but only when viewing it in that context.<br><br> You probably only want to select multiple schedules if this theme is shared between all schedules.<br><br>', to='conference.Schedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='document',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.Theme'),
        ),
    ]
