# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_auto_20160610_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='_content_rendered',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='content',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='schedules',
        ),
        migrations.AddField(
            model_name='theme',
            name='primer',
            field=models.FileField(blank=True, upload_to=b'documents/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='primer_title',
            field=models.CharField(blank=True, help_text=b'The title for the primer document that will be shown to the user.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='theme',
            name='title',
            field=models.CharField(help_text=b'The title for this theme that will be shown to the user.', max_length=1024),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
