# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-05 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0003_auto_20160810_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='primer_title',
            field=models.CharField(blank=True, help_text=b'The title for the draft report document that will be shown to the user.', max_length=1024),
        ),
    ]
