# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 08:18
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import markitup.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text=b'An internal name for this block of content, to help identify it.', max_length=1024)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, help_text=b'Used to identify this block of content when we include it in pages.', populate_from=b'name', unique=True)),
                ('content', markitup.fields.MarkupField(blank=True, no_rendered_field=True)),
                ('_content_rendered', models.TextField(blank=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
