# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 09:41
from __future__ import unicode_literals

from django.db import migrations

def add_block(apps, schema_editor):
    Block = apps.get_model("blocks", "Block")
    Block.objects.get_or_create(slug="homepage-post-stream", defaults={
        "name": "Homepage post-stream",
        "content": """### The event is over

Thank you to the many individuals on our production team who made this event possible.

Come back shortly to find videos, write-ups and other materials on this website."""
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_block)
    ]
