# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-07 17:42
from __future__ import unicode_literals

import cms.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('cms', '0002_auto_20170307_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', wagtail.wagtailcore.fields.StreamField([('heading', cms.blocks.HeadingBlock()), ('text', cms.blocks.TextBlock()), ('links', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'name', cms.blocks.HeadingBlock()), (b'start', wagtail.wagtailcore.blocks.DateTimeBlock(label=b'Start date/time')), (b'end', wagtail.wagtailcore.blocks.DateTimeBlock(label=b'End date/time')), (b'location', cms.blocks.TextBlock()), (b'link', wagtail.wagtailcore.blocks.URLBlock(required=False)), (b'schedule', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[(1, 'Symposium'), (2, 'Workshop')]))]), template='cms/blocks/events.html')), ('divider', cms.blocks.DividerBlock())], default=[])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
