# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-08 09:58
from __future__ import unicode_literals

import cms.blocks
from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_eventspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventspage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField([('heading', cms.blocks.HeadingBlock()), ('text', cms.blocks.TextBlock()), ('events', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'name', cms.blocks.HeadingBlock()), (b'start', wagtail.wagtailcore.blocks.DateTimeBlock(label=b'Start date/time')), (b'end', wagtail.wagtailcore.blocks.DateTimeBlock(label=b'End date/time')), (b'location', cms.blocks.TextBlock()), (b'link', wagtail.wagtailcore.blocks.URLBlock(required=False)), (b'schedule', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('conference', 'Symposium'), ('workshop', 'Workshop')], required=False))]), template='cms/blocks/events.html')), ('divider', cms.blocks.DividerBlock())], default=[]),
        ),
    ]
