# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-17 15:40
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_research_researchindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='excerpt',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
