# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-08 13:44
from __future__ import unicode_literals

import cms.blocks
from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20170308_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField([('mission', cms.blocks.MissionBlock()), ('heading', cms.blocks.HeadingBlock()), ('divider', cms.blocks.DividerBlock()), ('video', cms.blocks.YouTubeBlock()), ('features', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), (b'text', wagtail.wagtailcore.blocks.RichTextBlock()), (b'links', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'text', wagtail.wagtailcore.blocks.CharBlock(required=True)), (b'page', wagtail.wagtailcore.blocks.PageChooserBlock())])))]), icon='list-ul', template='cms/blocks/features.html')), ('columns', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), (b'text', wagtail.wagtailcore.blocks.RichTextBlock())]), icon='list-ul', template='cms/blocks/columns.html')), ('mailinglist', wagtail.wagtailcore.blocks.StructBlock([(b'title', cms.blocks.HeadingBlock()), (b'intro', cms.blocks.TextBlock(required=False)), (b'list_id', wagtail.wagtailcore.blocks.CharBlock(help_text=b'The list ID for your Mailchimp link (default is 581a2ce967)', required=False))]))], default=[]),
        ),
        migrations.AlterField(
            model_name='researchpage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField([('heading', cms.blocks.HeadingBlock()), ('text', cms.blocks.TextBlock()), ('links', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'title', cms.blocks.HeadingBlock()), (b'subtitle', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'description', wagtail.wagtailcore.blocks.RichTextBlock(required=False)), (b'thumbnail', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), (b'page', wagtail.wagtailcore.blocks.PageChooserBlock(required=False)), (b'external_link', wagtail.wagtailcore.blocks.URLBlock(required=False))]), icon='link', template='cms/blocks/featured_links.html')), ('divider', cms.blocks.DividerBlock())], default=[]),
        ),
    ]
