# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-20 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0029_standingcommittee'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('cms', '0007_eventsindexpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.RichTextField()),
                ('start', models.DateField(verbose_name='Start date/time')),
                ('end', models.DateField(verbose_name='End date/time')),
                ('location', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='conference.Schedule')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
