# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-08 14:35
from __future__ import unicode_literals

import cms.blocks
from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20170308_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplepage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField([('heading', cms.blocks.HeadingBlock()), ('text', cms.blocks.TextBlock()), ('people', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'name', wagtail.wagtailcore.blocks.CharBlock(required=True)), (b'position', wagtail.wagtailcore.blocks.CharBlock()), (b'organisation', wagtail.wagtailcore.blocks.CharBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'page', wagtail.wagtailcore.blocks.PageChooserBlock(required=False))]), icon='group', template='cms/blocks/people.html')), ('divider', cms.blocks.DividerBlock())], default=[]),
        ),
    ]
