# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-20 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end',
            field=models.DateTimeField(verbose_name='End date/time'),
        ),
        migrations.AlterField(
            model_name='events',
            name='start',
            field=models.DateTimeField(verbose_name='Start date/time'),
        ),
    ]
