# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-20 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20170220_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
