# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-07 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20170307_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peoplepage',
            old_name='people',
            new_name='content',
        ),
    ]
