# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-07 14:10
from __future__ import unicode_literals

import cms.blocks
from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('cms', '0021_auto_20170307_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personindexpage',
            name='page_ptr',
        ),
        migrations.AlterField(
            model_name='peoplepage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField([('heading', cms.blocks.HeadingBlock()), ('text', cms.blocks.TextBlock()), ('people', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'name', wagtail.wagtailcore.blocks.CharBlock(required=True)), (b'position', wagtail.wagtailcore.blocks.CharBlock()), (b'organisation', wagtail.wagtailcore.blocks.CharBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock())]), icon='group', template='cms/blocks/people.html')), ('divider', cms.blocks.DividerBlock())], default=[]),
        ),
        migrations.DeleteModel(
            name='PersonIndexPage',
        ),
    ]
