# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 16:25
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import markitup.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, help_text=b'An internal name for this page, to help identify it.', max_length=1024)),
                ('title', models.CharField(help_text=b'The page title that will be shown to the user.', max_length=1024)),
                ('slug', autoslug.fields.AutoSlugField(editable=True, help_text=b'Used to make a nice url for this Page.', populate_from=b'title', unique=True)),
                ('content', markitup.fields.MarkupField(blank=True, no_rendered_field=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('_content_rendered', models.TextField(blank=True, editable=False)),
                ('parent_page', models.ForeignKey(blank=True, help_text=b'If this page belongs in a section underneath another, choose that parent page here.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_pages', to='pages.Page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
