# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20160609_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='schedules',
            field=models.ManyToManyField(blank=True, help_text=b"Which schedules is this related to? If a schedule is private, this page will be kept private too, but only when viewing it in that context.<br><br>You probably only want to select multiple schedules if this is a public page that's shared between all schedules (like the privacy page).<br><br>You can't set this individually on child pages, set it once on the top level page and it will be applied to all the children automatically.<br><br>", to='conference.Schedule'),
        ),
    ]
