# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 16:25
from __future__ import unicode_literals

import conference.models
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_auto_20160527_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=conference.models.person_photo_upload_to),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=conference.models.person_photo_upload_to),
        ),
    ]
