# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import markitup.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_auto_20160527_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='_long_description_rendered',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='long_description',
            field=markitup.fields.MarkupField(no_rendered_field=True),
        ),
    ]
