# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import markitup.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_auto_20160531_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='_biography_rendered',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='speaker',
            name='_biography_rendered',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='biography',
            field=markitup.fields.MarkupField(blank=True, no_rendered_field=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='biography',
            field=markitup.fields.MarkupField(blank=True, no_rendered_field=True),
        ),
    ]
