# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0006_auto_20160602_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='private',
            field=models.BooleanField(default=False, help_text=b'Is this schedule for a private event?<br>If this box is checked, this schedule and anything connected to it will force you to log in to view it.'),
        ),
    ]
