# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0007_schedule_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.Schedule'),
        ),
    ]
