# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0008_attendee_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='facebook',
        ),
    ]
