# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0010_auto_20160614_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='kind',
            field=models.CharField(choices=[(b'TALK', b'Talk'), (b'OTHER', b'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='slot',
            name='name',
            field=models.CharField(blank=True, help_text=b'Text that will be shown to the user for this slot if no presentation is associated with it instead.', max_length=1024),
        ),
    ]
