# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import markitup.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0012_slot_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='_short_description_rendered',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='slot',
            name='short_description',
            field=markitup.fields.MarkupField(blank=True, help_text=b"Extra text to display under this slot's name in the  schedule. Useful if you need a description but don't want to associate a whole presentation with it.", no_rendered_field=True),
        ),
    ]
