# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import markitup.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0013_auto_20160614_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='_introduction_rendered',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='introduction',
            field=markitup.fields.MarkupField(blank=True, help_text=b"The text that's shown at the top of the schedule, before the slots.", no_rendered_field=True),
        ),
    ]
