# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0014_auto_20160614_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='_biography_rendered',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='website',
        ),
        migrations.AddField(
            model_name='attendee',
            name='organisation',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='speaker',
            name='organisation',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
