# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0015_auto_20160615_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='external_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
