# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0016_attendee_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='biography',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='attendee',
            name='title',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
