# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 10:41
from __future__ import unicode_literals

import conference.models
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0017_auto_20160616_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='biography',
            field=models.TextField(blank=True, help_text=b'Maximum 250 words.', max_length=1500),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text=b'Photos must be at least 500px by 500px.', upload_to=conference.models.person_photo_upload_to),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text=b'Photos must be at least 500px by 500px.', upload_to=conference.models.person_photo_upload_to),
        ),
    ]
