# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0018_auto_20160617_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='title',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
