# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0019_speaker_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text=b'An internal name for this stream, to help you recognise it', max_length=1024)),
                ('youtube_link', models.URLField(help_text=b"The url for the live stream's page on YouTube.<br>We can extract everything we need to embed it from that.", max_length=1024)),
                ('live', models.BooleanField(default=False, help_text=b"Is this stream live now?<br>Tick the box to make it appear on the homepage. Note: thiswill replace any stream that's currently live.")),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
