# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0020_livestream'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['start']},
        ),
        migrations.AlterField(
            model_name='livestream',
            name='live',
            field=models.BooleanField(default=False, help_text=b"Is this stream live now?<br>Tick the box to make it appear on the homepage.<br>Note: this will replace any stream that's currently live."),
        ),
    ]
