# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0021_auto_20160701_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='youtube_link',
            field=models.URLField(blank=True, help_text=b"The url for the presentation's video on YouTube.<br>We can extract everything we need to embed it from that.", max_length=1024),
        ),
    ]
