# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import markitup.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0022_presentation_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='_short_description_rendered',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='short_description',
            field=markitup.fields.MarkupField(no_rendered_field=True),
        ),
    ]
