# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0023_auto_20160727_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text=b"If this presentation isn't associated with a slot in a schedule directly, but needs to be visible in that schedule, e.g. a lightning talk, set the schedule here", null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.Schedule'),
        ),
    ]
