# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-20 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0025_auto_20161020_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisertype',
            name='name',
            field=models.CharField(max_length=1024),
        ),
    ]
