# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-24 17:16
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0025_auto_20161124_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, help_text=b'Used to make a nice url for the page that displays this schedule.', populate_from=b'name'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set([('slug', 'year')]),
        ),
    ]
