# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-20 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0026_auto_20161020_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organiser',
            name='organiser_type',
        ),
        migrations.AddField(
            model_name='organiser',
            name='organiser_type',
            field=models.ManyToManyField(to='conference.OrganiserType'),
        ),
    ]
