# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-04 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0027_auto_20161020_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendee',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='organiser',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='speaker',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='attendee',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text=b'Order in which the person will appear in a list.'),
        ),
        migrations.AddField(
            model_name='organiser',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text=b'Order in which the person will appear in a list.'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text=b'Order in which the person will appear in a list.'),
        ),
    ]
