# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-15 15:49
from __future__ import unicode_literals

import autoslug.fields
import conference.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conference', '0028_auto_20161104_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandingCommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1024)),
                ('slug', autoslug.fields.AutoSlugField(editable=True, help_text=b'Used to make a nice url for the page that displays this person.', populate_from=b'name', unique=True)),
                ('photo', sorl.thumbnail.fields.ImageField(blank=True, help_text=b'Photos must be at least 500px by 500px.', upload_to=conference.models.person_photo_upload_to)),
                ('twitter_username', models.CharField(blank=True, max_length=15)),
                ('title', models.CharField(blank=True, max_length=1024)),
                ('organisation', models.CharField(blank=True, max_length=1024)),
                ('sort_order', models.IntegerField(blank=True, default=0, help_text=b'Order in which the person will appear in a list.')),
                ('website', models.URLField(blank=True, max_length=1024)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conference_standingcommittee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
    ]
