# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-28 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0029_standingcommittee'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE "conference_slot" ALTER COLUMN "end" TYPE timestamp USING \'today\'::date + "end"::time;'),
        migrations.RunSQL('ALTER TABLE "conference_slot" ALTER COLUMN "start" TYPE timestamp USING \'today\'::date + "start"::time;'),
    ]
