# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-16 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0029_standingcommittee'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganiserScheduleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Organiser')),
                ('organiser_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.OrganiserType')),
                ('schedule', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='conference.Schedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='organiser',
            name='organiser_schedule_type',
            field=models.ManyToManyField(related_name='organiser_schedule_type', through='conference.OrganiserScheduleType', to='conference.OrganiserType'),
        ),
    ]
