# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-21 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0030_auto_20170616_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='attendee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.Attendee'),
        ),
    ]
