# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-28 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0030_auto_20170228_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
