# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-16 17:06
from __future__ import unicode_literals

from django.db import migrations


def migrate_organisers(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Organiser = apps.get_model('conference', 'Organiser')
    OrganiserScheduleType = apps.get_model('conference', 'OrganiserScheduleType')
    Schedule = apps.get_model('conference', 'Schedule')

    # this is specific to the data in the FATML DB so if we don't
    # find this schedule then it's fine
    try:
        schedule = Schedule.objects.get(slug='2016')

        for organizer in Organiser.objects.all():
            for org_type in organizer.organiser_type.all():
                OrganiserScheduleType.objects.using(db_alias).create(
                    organiser=organizer,
                    organiser_type=org_type,
                    schedule=schedule
                )
    except Schedule.DoesNotExist:
        pass


def unmigrate_organisers(apps, schema_editor):
    OrganiserScheduleType = apps.get_model('conference', 'OrganiserScheduleType')

    for org_sched_types in OrganiserScheduleType.objects.all():
        org_sched_types.organiser.organiser_type.add(org_sched_types.organiser_type)


class Migration(migrations.Migration):

    dependencies = [
            ('conference', '0030_auto_20161116_1754'),
    ]

    operations = [
        migrations.RunPython(migrate_organisers, unmigrate_organisers)
    ]
