# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-12 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0031_speaker_attendee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentation',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='presentation',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text=b'Order in which the presentation will appear in a list.'),
        ),
    ]
