# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-20 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0032_auto_20170320_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='conference.Session'),
        ),
    ]
