# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-20 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import markitup.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0034_auto_20170320_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='long_description',
            field=markitup.fields.MarkupField(blank=True, no_rendered_field=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='short_description',
            field=markitup.fields.MarkupField(blank=True, no_rendered_field=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(help_text=b'This will be shown to the user for this session if no presentations are associated with it instead.', max_length=1024),
        ),
    ]
