# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-20 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0035_auto_20170320_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='additional_speakers',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='primary_speaker',
        ),
        migrations.AddField(
            model_name='presentation',
            name='speakers',
            field=models.ManyToManyField(related_name='presentations', to='conference.Speaker'),
        ),
    ]
