# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-21 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0036_auto_20170320_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentation',
            options={'ordering': ['session__slot__start', 'session__room__name']},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['slot__start', 'room__name']},
        ),
    ]
