# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-21 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0037_auto_20170321_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='kind',
            field=models.CharField(choices=[(b'KEYNOTE', b'Keynote'), (b'TALK', b'Talk'), (b'OTHER', b'Other')], max_length=100),
        ),
    ]
