# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-06 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0038_auto_20170321_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendee',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='organiser',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='speaker',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='standingcommittee',
            options={'ordering': ['name']},
        ),
    ]
