# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-28 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0039_auto_20170406_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='slideshare_link',
            field=models.URLField(blank=True, help_text=b"The url for the presentation's slides on SlideShare.<br>We can extract everything we need to embed it from that.", max_length=1024),
        ),
    ]
