# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-28 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0040_presentation_slideshare_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='slideshare_embed_html',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
