# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-04 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0041_presentation_slideshare_embed_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='youtube_embed_html',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
