# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-04-04 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0042_presentation_youtube_embed_html'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentation',
            options={'ordering': ['order', 'session__slot__start', 'session__room__name']},
        ),
        migrations.AddField(
            model_name='presentation',
            name='order',
            field=models.IntegerField(default=0, help_text=b'Use to override the order in which presentations appear within a slot. Lower numbers appear first.'),
        ),
    ]
