# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-04-11 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0043_auto_20180404_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='schedules',
            field=models.ManyToManyField(blank=True, to='conference.Schedule'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_schedule', to='conference.Schedule'),
        ),
    ]
