# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-04-11 09:49
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    Attendee = apps.get_model("conference", "Attendee")
    for attendee in Attendee.objects.all():
        attendee.schedules.add(attendee.schedule)


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0044_auto_20180411_1049'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
