# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-04-11 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0045_auto_20180411_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='schedule',
        ),
    ]
