# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-01 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0046_remove_attendee_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='prezi_link',
            field=models.URLField(blank=True, help_text=b'The url for the presentation on Prezi.<br>We can extract everything we need to embed it from that.', max_length=1024),
        ),
    ]
