# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 11:35
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import markitup.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, help_text=b'An internal name for this category, to help identify it.', max_length=1024)),
                ('title', models.CharField(help_text=b'The title for this category that will be shown to the user.', max_length=1024)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, help_text=b'Used to identify this category when we link to it.', populate_from=b'title', unique=True)),
                ('introduction', markitup.fields.MarkupField(blank=True, help_text=b'This will be shown above the documents in this category.', no_rendered_field=True)),
                ('_introduction_rendered', models.TextField(blank=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, help_text=b'An internal name for this document, to help identify it.', max_length=1024)),
                ('title', models.CharField(help_text=b'The title for this document that will be shown to the user.', max_length=1024)),
                ('description', markitup.fields.MarkupField(blank=True, no_rendered_field=True)),
                ('file', models.FileField(upload_to=b'documents/')),
                ('_description_rendered', models.TextField(blank=True, editable=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='resources.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
